# Generated by Django 3.1.4 on 2021-06-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created',)},
        ),
    ]
